# Generated by Django 4.2.5 on 2023-12-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivities',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'UserActivities'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hod',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_confirmed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hod',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
