# Generated by Django 4.2.5 on 2023-12-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0004_customuser_matricle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='matricle',
            field=models.CharField(blank=True, default=70208, max_length=15),
        ),
    ]
