# Generated by Django 4.2.5 on 2023-12-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0005_alter_customuser_matricle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='matricle',
            field=models.CharField(blank=True, default=18277, max_length=15),
        ),
    ]
