# Generated by Django 5.0.1 on 2024-08-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_one', models.CharField(max_length=255)),
                ('message_two', models.CharField(blank=True, max_length=255, null=True)),
                ('complain_type', models.CharField(blank=True, choices=[('request', 'request'), ('complain', 'complain')], max_length=15, null=True)),
                ('status', models.BooleanField(default=True)),
                ('ending_at', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_one', models.CharField(max_length=255)),
                ('message_two', models.CharField(blank=True, max_length=255, null=True)),
                ('target', models.CharField(blank=True, choices=[('schools', 'schools'), ('domains', 'domains'), ('specialty', 'specialty'), ('custom', 'custom')], max_length=15, null=True)),
                ('custom', models.CharField(blank=True, choices=[('unassigned_students', 'unassigned_students'), ('fees', 'fees'), ('announcement', 'announcement')], max_length=50, null=True)),
                ('role', models.CharField(blank=True, choices=[('admin', 'admin'), ('teacher', 'teacher'), ('student', 'student')], max_length=15, null=True)),
                ('noti_type', models.CharField(blank=True, choices=[('time', 'time'), ('fees', 'fees'), ('announcement', 'announcement'), ('results', 'results')], max_length=15, null=True)),
                ('status', models.BooleanField(default=True)),
                ('ending_at', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('item', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'UserActivities',
                'ordering': ('-updated_at',),
            },
        ),
    ]
