# Generated by Django 5.0.1 on 2024-08-11 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_control', '0002_initial'),
        ('noti_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complain_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complain',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complain_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='domains',
            field=models.ManyToManyField(blank=True, to='app_control.domain'),
        ),
        migrations.AddField(
            model_name='notification',
            name='schools',
            field=models.ManyToManyField(blank=True, to='app_control.schoolinfo'),
        ),
        migrations.AddField(
            model_name='notification',
            name='specialty',
            field=models.ManyToManyField(blank=True, to='app_control.specialty'),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_activity_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
