# Generated by Django 5.0.1 on 2024-11-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noti_control', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='message_one',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='message_two',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message_one',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message_two',
        ),
        migrations.AddField(
            model_name='complain',
            name='message',
            field=models.TextField(default='Message One'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default='Message One'),
            preserve_default=False,
        ),
    ]
