# Generated by Django 5.0.1 on 2024-10-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=35, null=True)),
                ('number', models.CharField(blank=True, max_length=35, null=True)),
                ('year', models.CharField(default='2023/2024')),
                ('balance', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Accounts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ActivationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Activation',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SchoolFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_charges', models.IntegerField(default=1000)),
                ('platform_paid', models.BooleanField(default=False)),
                ('balance', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'School Fees',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('BANK', 'BANK'), ('MTN', 'MTN'), ('ORANGE', 'ORANGE'), ('DIRECT', 'DIRECT')], max_length=255)),
                ('account', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.CharField(default='Edit', max_length=255)),
                ('ref', models.CharField(blank=True, max_length=35, null=True)),
                ('operation_type', models.CharField(default='income', max_length=8)),
                ('origin', models.CharField(default='admin', max_length=8)),
                ('amount', models.IntegerField()),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('payer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('operator', models.CharField(blank=True, choices=[('MTN', 'MTN'), ('ORANGE', 'ORANGE')], max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TranscriptApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('PRINTED', 'PRINTED')], max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Transcript Applications',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('name', 'year'), name='unique_account'),
        ),
    ]
