# Generated by Django 5.0.1 on 2024-09-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_control', '0004_alter_account_options_account_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='year',
            field=models.CharField(default='2023/2024'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(choices=[('REGISTRATION', 'REGISTRATION'), ('TUITION', 'TUITION'), ('SCHOLARSHIP', 'SCHOLARSHIP')], max_length=255),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('name', 'year'), name='unique_account'),
        ),
    ]
