# Generated by Django 5.0.1 on 2024-09-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_control', '0005_account_year_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='operation_type',
            field=models.CharField(default='income', max_length=8),
        ),
    ]
