# Generated by Django 5.0.1 on 2024-09-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_control', '0007_transactions_account_alter_transactions_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='from_account',
            field=models.CharField(blank=True, default=10, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='to_account',
            field=models.CharField(blank=True, default=10, max_length=50, null=True),
        ),
    ]
