# Generated by Django 5.0.1 on 2024-09-20 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_control', '0011_alter_transactions_account_and_more'),
        ('user_control', '0003_alter_userprofile_matricle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='origin',
            field=models.CharField(default='admin', max_length=8),
        ),
        migrations.CreateModel(
            name='TranscriptApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('PRINTED', 'PRINTED')], max_length=20)),
                ('approved_at', models.DateTimeField()),
                ('printed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trancript_approved_by', to=settings.AUTH_USER_MODEL)),
                ('printed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript_printed_by', to=settings.AUTH_USER_MODEL)),
                ('userprofile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transcript_userprofile', to='user_control.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Transcript Applications',
                'ordering': ('-created_at',),
            },
        ),
    ]
