# Generated by Django 5.0.1 on 2024-08-11 05:56

import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('school_name', models.CharField(max_length=50)),
                ('school_type', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('University', 'University'), ('Vocational', 'Vocational')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
    ]
