# Generated by Django 5.0.1 on 2024-10-30 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prim_fees_control', '0001_initial'),
        ('prim_user_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='primactivationkey',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primpayment_method_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='primactivationkey',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primpayment_method_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='primschoolfees',
            name='primaryprofile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primschoolfees_userprofile', to='prim_user_control.primaryprofile'),
        ),
        migrations.AddField(
            model_name='primtransactions',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prim_transaction_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='primtransactions',
            name='primschoolfees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prim_fees_control.primschoolfees'),
        ),
        migrations.AddField(
            model_name='primtransactions',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prim_transaction_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
