# Generated by Django 5.0.1 on 2024-10-30 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_control', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=13, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('pob', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ADMITTED', 'ADMITTED')], max_length=8)),
                ('emergency_name', models.CharField(max_length=30)),
                ('emergency_town', models.CharField(blank=True, max_length=30, null=True)),
                ('emergency_telephone', models.CharField(max_length=28)),
                ('program', models.CharField(choices=[('HND', 'HND'), ('BTS', 'BTS'), ('AQP', 'AQP'), ('BSC', 'BSC'), ('LICENSE', 'LICENSE'), ('MASTERS', 'MASTERS'), ('DPQ', 'DPQ'), ('OND', 'OND')], max_length=12)),
                ('level', models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500')], max_length=12)),
                ('session', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=12)),
                ('academic_year', models.CharField(max_length=10)),
                ('specialty_one', models.CharField(max_length=50)),
                ('specialty_two', models.CharField(max_length=50)),
                ('specialty_three', models.CharField(max_length=50)),
                ('campus', models.CharField(default='Campus-A', max_length=20)),
                ('admission_status', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('CREATING', 'CREATING'), ('UPDATING', 'UPDATING'), ('VERIFICATION', 'VERIFICATION'), ('ADMISSION', 'ADMISSION')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=19, unique=True)),
                ('matricle', models.CharField(blank=True, max_length=15, unique=True)),
                ('role', models.CharField(choices=[('superadmin', 'superadmin'), ('admin', 'admin'), ('teacher', 'teacher'), ('student', 'student'), ('data entry', 'data entry')], max_length=15)),
                ('password_set', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('hod', models.BooleanField(blank=True, default=False)),
                ('email_confirmed', models.BooleanField(blank=True, default=False)),
                ('first_name', models.CharField(blank=True, max_length=15, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('telephone', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('title', models.CharField(blank=True, choices=[('Prof', 'Prof'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Engr', 'Engr'), ('Dr', 'Dr'), ('Miss', 'Miss')], max_length=15, null=True)),
                ('pob', models.CharField(blank=True, max_length=25, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('parent', models.CharField(blank=True, max_length=30, null=True)),
                ('parent_telephone', models.CharField(blank=True, max_length=28, null=True)),
                ('prefix', models.CharField(blank=True, max_length=28, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('school', models.ManyToManyField(related_name='user_shool', to='app_control.schoolinfo')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.CharField(choices=[('light', 'light'), ('dark', 'dark'), ('system', 'system')], default='light', max_length=15)),
                ('lang', models.CharField(choices=[('en', 'En'), ('fr', 'Fr'), ('de', 'De'), ('es', 'Es')], default='En', max_length=15)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appearance_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Administration', 'Administration'), ('Student', 'Student'), ('Lecturer', 'Lecturer'), ('Accounting', 'Accounting')], max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='dept',
            field=models.ManyToManyField(blank=True, to='user_control.department'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DE', 'DE'), ('Accounting', 'Accounting')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='page',
            field=models.ManyToManyField(blank=True, to='user_control.page'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Programs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricle', models.CharField(blank=True, max_length=15, null=True)),
                ('active', models.BooleanField(default=True)),
                ('session', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='Morning', max_length=15)),
                ('code', models.ImageField(blank=True, null=True, upload_to='code')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('program', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='userprofile_program', to='user_control.program')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofile_specialty', to='app_control.specialty')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userprofile_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(fields=('specialty', 'user'), name='unique_profile'),
        ),
    ]
