# Generated by Django 5.0.1 on 2024-08-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='matricle',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
