# Generated by Django 5.0.1 on 2024-08-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0002_userprofile_matricle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='matricle',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
