# Generated by Django 5.0.1 on 2024-12-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0003_customuser_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinscription',
            name='program',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
