# Generated by Django 5.0.1 on 2024-09-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0003_alter_userprofile_matricle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('telephone', models.CharField(max_length=13, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('father_first_name', models.CharField(max_length=30)),
                ('father_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('mother_first_name', models.CharField(max_length=30)),
                ('mother_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('parent_telephone', models.CharField(max_length=28)),
                ('parent_email', models.CharField(blank=True, max_length=28, null=True)),
                ('pob', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('region', models.CharField(blank=True, max_length=28, null=True)),
                ('division', models.CharField(blank=True, max_length=28, null=True)),
                ('subdivision', models.CharField(blank=True, max_length=28, null=True)),
                ('academic_year', models.CharField(max_length=28)),
                ('specialty_one', models.CharField(max_length=28)),
                ('specialty_two', models.CharField(max_length=28)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
