# Generated by Django 5.0.1 on 2024-12-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0004_alter_preinscription_program_alter_program_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinscription',
            name='action',
            field=models.CharField(choices=[('CREATING', 'CREATING'), ('UPDATING', 'UPDATING'), ('VERIFICATION', 'VERIFICATION'), ('ADMISSION', 'ADMISSION')], max_length=15),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='campus',
            field=models.CharField(default='Campus-A', max_length=50),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='emergency_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='emergency_telephone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='emergency_town',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='pob',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='program',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='specialty_one',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='specialty_three',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='specialty_two',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ADMITTED', 'ADMITTED')], max_length=15),
        ),
    ]
