# Generated by Django 5.0.1 on 2024-12-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0005_alter_preinscription_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='matricle',
        ),
        migrations.AlterField(
            model_name='appearance',
            name='dark_mode',
            field=models.CharField(choices=[('light', 'light'), ('dark', 'dark'), ('system', 'system')], default='light', max_length=255),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='lang',
            field=models.CharField(choices=[('en', 'En'), ('fr', 'Fr'), ('de', 'De'), ('es', 'Es')], default='En', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pob',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='title',
            field=models.CharField(blank=True, choices=[('Prof', 'Prof'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Engr', 'Engr'), ('Dr', 'Dr'), ('Miss', 'Miss')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='action',
            field=models.CharField(choices=[('CREATING', 'CREATING'), ('UPDATING', 'UPDATING'), ('VERIFICATION', 'VERIFICATION'), ('ADMISSION', 'ADMISSION')], max_length=20),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='emergency_telephone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='telephone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
