# Generated by Django 5.0.1 on 2024-09-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0005_preinscription_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preinscription',
            old_name='father_first_name',
            new_name='emergency_name',
        ),
        migrations.RenameField(
            model_name='preinscription',
            old_name='parent_telephone',
            new_name='emergency_telephone',
        ),
        migrations.RenameField(
            model_name='preinscription',
            old_name='father_last_name',
            new_name='emergency_town',
        ),
        migrations.RemoveField(
            model_name='preinscription',
            name='about',
        ),
        migrations.RemoveField(
            model_name='preinscription',
            name='division',
        ),
        migrations.RemoveField(
            model_name='preinscription',
            name='mother_first_name',
        ),
        migrations.RemoveField(
            model_name='preinscription',
            name='mother_last_name',
        ),
        migrations.RemoveField(
            model_name='preinscription',
            name='parent_email',
        ),
        migrations.RemoveField(
            model_name='preinscription',
            name='region',
        ),
        migrations.RemoveField(
            model_name='preinscription',
            name='subdivision',
        ),
    ]
