# Generated by Django 5.0.1 on 2024-12-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0006_remove_customuser_logo_remove_userprofile_matricle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo'),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='specialty_three',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
