# Generated by Django 5.0.1 on 2024-08-11 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sec_fees_control', '0001_initial'),
        ('sec_user_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activationkey',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secpayment_method_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activationkey',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secpayment_method_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secschoolfees',
            name='secondaryprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='secschoolfees_userprofile', to='sec_user_control.secondaryprofile'),
        ),
        migrations.AddField(
            model_name='sectransactions',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sec_transaction_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectransactions',
            name='secschoolfees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sec_fees_control.secschoolfees'),
        ),
        migrations.AddField(
            model_name='sectransactions',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sec_transaction_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
