# Generated by Django 5.0.1 on 2024-08-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Campus-A', 'Campus-A'), ('Campus-B', 'Campus-B'), ('Campus-C', 'Campus-C'), ('Campus-D', 'Campus-D'), ('Campus-E', 'Campus-E'), ('Campus-F', 'Campus-F'), ('Campus-G', 'Campus-G'), ('Campus-H', 'Campus-H')], default='I', max_length=15)),
                ('region', models.CharField(choices=[('ADAMAWA', 'ADAMAWA'), ('CENTRE', 'CENTER'), ('EAST', 'EAST'), ('FAR NORTH', 'FAR NORTH'), ('LITTORAL', 'LITTORAL'), ('NORTH', 'NORTH'), ('NORTH WEST', 'NORTH WEST'), ('SOUTH', 'SOUTH'), ('SOUTH WEST', 'SOUTH WEST'), ('WEST', 'WEST')], default='I', max_length=15)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('course_type', models.CharField(choices=[('Fundamental', 'Fundamental'), ('Transversal', 'Transversal'), ('Professional', 'Professional')], default='Fundamental', max_length=15)),
                ('semester', models.CharField(choices=[('I', 'I'), ('II', 'II')], default='I', max_length=15)),
                ('course_credit', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('assigned', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('hours', models.IntegerField(default=0)),
                ('hours_left', models.IntegerField(default=0)),
                ('date_assigned', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='MainCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('I', 'I'), ('II', 'II')], default='I', max_length=15)),
                ('ca', models.BooleanField(default=False)),
                ('exam', models.BooleanField(default=False)),
                ('resit', models.BooleanField(default=False)),
                ('portal_ca', models.BooleanField(default=False)),
                ('portal_exam', models.BooleanField(default=False)),
                ('portal_resit', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('exam', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('resit', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('average', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('validated', models.BooleanField(default=False)),
                ('publish_ca', models.BooleanField(default=False)),
                ('publish_exam', models.BooleanField(default=False)),
                ('publish_resit', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('status', models.BooleanField(default=True)),
                ('back_end', models.CharField(default='http://127.0.0.1:8000', max_length=75)),
                ('front_end', models.CharField(default='http://apitest.econneq.com', max_length=75)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_type', models.CharField(choices=[('Section-P', 'Section-P'), ('Section-S', 'Section-S'), ('Section-H', 'Section-H'), ('Section-V', 'Section-V')], default='Secondary', max_length=15)),
                ('main_school', models.BooleanField(default=False)),
                ('school_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('town', models.CharField(max_length=10)),
                ('region', models.CharField(choices=[('ADAMAWA', 'ADAMAWA'), ('CENTRE', 'CENTER'), ('EAST', 'EAST'), ('FAR NORTH', 'FAR NORTH'), ('LITTORAL', 'LITTORAL'), ('NORTH', 'NORTH'), ('NORTH WEST', 'NORTH WEST'), ('SOUTH', 'SOUTH'), ('SOUTH WEST', 'SOUTH WEST'), ('WEST', 'WEST')], max_length=12)),
                ('country', models.CharField(default='CAMEROON', max_length=12)),
                ('po_box', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('niu', models.CharField(max_length=50)),
                ('telephone_one', models.CharField(max_length=15)),
                ('telephone_two', models.CharField(max_length=15)),
                ('website', models.CharField(max_length=45)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('tuition', models.IntegerField(default=0)),
                ('payment_one', models.IntegerField(default=0)),
                ('payment_two', models.IntegerField(default=0)),
                ('payment_three', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
