# Generated by Django 5.0.1 on 2024-11-10 21:22

import django.db.models.deletion
import higher_control.app_control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0003_alter_maincourse_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coursemodule_course', to='app_control.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=higher_control.app_control.models.upload_to)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courseupload_course', to='app_control.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseModuleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('course_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coursemoduledetail_coursemodule', to='app_control.coursemodule')),
                ('file', models.ManyToManyField(related_name='detail_file', to='app_control.courseupload')),
            ],
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='file',
            field=models.ManyToManyField(related_name='modulew_file', to='app_control.courseupload'),
        ),
    ]
