# Generated by Django 5.0.1 on 2024-08-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0004_alter_result_matricle'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainspecialty',
            name='specialty_name_short',
            field=models.CharField(default='Edit', max_length=5),
        ),
    ]
