# Generated by Django 5.0.1 on 2024-11-10 21:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0004_coursemodule_courseupload_coursemoduledetail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseupload',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursemoduledetail',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
