# Generated by Django 5.0.1 on 2024-11-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0005_rename_create_at_courseupload_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='version',
            field=models.CharField(default='1.0.0', max_length=10),
            preserve_default=False,
        ),
    ]
