# Generated by Django 5.0.1 on 2024-11-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0006_schoolinfo_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolidentification',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='platform_charges',
            field=models.IntegerField(default=1000),
        ),
    ]
