# Generated by Django 5.0.1 on 2024-09-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0006_syscategory_sysconstant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysconstant',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
