# Generated by Django 5.0.1 on 2024-09-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0007_alter_sysconstant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='registration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='syscategory',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='sysconstant',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
