# Generated by Django 5.0.1 on 2024-11-27 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0007_schoolidentification_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolinfo',
            name='platform_charges',
        ),
        migrations.AddField(
            model_name='campus',
            name='latitude',
            field=models.CharField(default=3.8436864, max_length=10),
        ),
        migrations.AddField(
            model_name='campus',
            name='location',
            field=models.CharField(default='Douala', max_length=40),
        ),
        migrations.AddField(
            model_name='campus',
            name='longitude',
            field=models.CharField(default=11.4917376, max_length=10),
        ),
        migrations.AddField(
            model_name='campus',
            name='radius',
            field=models.IntegerField(default=100, max_length=3),
        ),
        migrations.AddField(
            model_name='schoolidentification',
            name='support_number_one',
            field=models.CharField(default='690640864', max_length=15),
        ),
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(choices=[('Campus-A', 'Campus-A'), ('Campus-B', 'Campus-B'), ('Campus-C', 'Campus-C'), ('Campus-D', 'Campus-D'), ('Campus-E', 'Campus-E'), ('Campus-F', 'Campus-F'), ('Campus-G', 'Campus-G'), ('Campus-H', 'Campus-H')], default='Campus-A', max_length=15),
        ),
        migrations.AlterField(
            model_name='campus',
            name='region',
            field=models.CharField(choices=[('ADAMAWA', 'ADAMAWA'), ('CENTRE', 'CENTER'), ('EAST', 'EAST'), ('FAR NORTH', 'FAR NORTH'), ('LITTORAL', 'LITTORAL'), ('NORTH', 'NORTH'), ('NORTH WEST', 'NORTH WEST'), ('SOUTH', 'SOUTH'), ('SOUTH WEST', 'SOUTH WEST'), ('WEST', 'WEST')], default='Littoral', max_length=15),
        ),
        migrations.CreateModel(
            name='SettingHigher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_message_main', models.CharField(default='Welcome')),
                ('logo_main512', models.CharField(default='/images/logo/LogoEconneq.png')),
                ('logo_main256', models.CharField(default='/images/logo/LogoEconneq.png')),
                ('prefix', models.CharField(default='TEST', max_length=10)),
                ('method', models.IntegerField(default=2)),
                ('landing_message', models.CharField(default='Welcome To, Econneq', max_length=255)),
                ('ca_limit', models.IntegerField(default=30)),
                ('exam_limit', models.IntegerField(default=70)),
                ('resit_limit', models.IntegerField(default=70)),
                ('registration_seperate_tuition', models.BooleanField(default=True)),
                ('schoolfees_control', models.CharField(default='0.50, 0.80, 0.99, 1, 1, 1', max_length=255)),
                ('logo512', models.ImageField(blank=True, null=True, upload_to='logo_higher/')),
                ('logo256', models.ImageField(blank=True, null=True, upload_to='logo_higher/')),
                ('bg_transcript', models.ImageField(blank=True, null=True, upload_to='transcript_higher/')),
                ('bg_slip', models.ImageField(blank=True, null=True, upload_to='slip_higher/')),
                ('colors', models.CharField(default='bg-teal-700, bg-teal-700', max_length=255)),
                ('campus', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='schoolhigher_campus', to='app_control.campus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
