# Generated by Django 5.0.1 on 2024-09-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0008_specialty_registration_alter_syscategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='director',
            field=models.CharField(default='edit', max_length=50),
        ),
    ]
