# Generated by Django 5.0.1 on 2024-11-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0008_remove_schoolinfo_platform_charges_campus_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='radius',
            field=models.IntegerField(default=100),
        ),
    ]
