# Generated by Django 5.0.1 on 2024-11-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0009_alter_campus_radius'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='location',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='radius',
        ),
        migrations.AddField(
            model_name='schoolidentification',
            name='support_number_two',
            field=models.CharField(default='690640864', max_length=15),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='latitude',
            field=models.CharField(default=3.8436864, max_length=10),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='longitude',
            field=models.CharField(default=11.4917376, max_length=10),
        ),
        migrations.AddField(
            model_name='settinghigher',
            name='address',
            field=models.CharField(default='Douala', max_length=20),
        ),
        migrations.AddField(
            model_name='settinghigher',
            name='director',
            field=models.CharField(default='edit', max_length=50),
        ),
        migrations.AddField(
            model_name='settinghigher',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='settinghigher',
            name='niu',
            field=models.CharField(default='NIU', max_length=50),
        ),
        migrations.AddField(
            model_name='settinghigher',
            name='po_box',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settinghigher',
            name='short_name',
            field=models.CharField(default='Name', max_length=20),
        ),
        migrations.AddField(
            model_name='settinghigher',
            name='telephone_one',
            field=models.CharField(default='670000000', max_length=15),
        ),
        migrations.AddField(
            model_name='settinghigher',
            name='telephone_two',
            field=models.CharField(default='690000000', max_length=15),
        ),
        migrations.AddField(
            model_name='settinghigher',
            name='town',
            field=models.CharField(default='Douala', max_length=10),
        ),
        migrations.AddField(
            model_name='settinghigher',
            name='website',
            field=models.CharField(default='https://test.e-conneq.com', max_length=45),
        ),
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(choices=[('Campus-A', 'Campus-A'), ('Campus-B', 'Campus-B'), ('Campus-C', 'Campus-C'), ('Campus-D', 'Campus-D'), ('Campus-E', 'Campus-E'), ('Campus-F', 'Campus-F'), ('Campus-G', 'Campus-G'), ('Campus-H', 'Campus-H')], default='I', max_length=15),
        ),
        migrations.AlterField(
            model_name='campus',
            name='region',
            field=models.CharField(choices=[('ADAMAWA', 'ADAMAWA'), ('CENTRE', 'CENTER'), ('EAST', 'EAST'), ('FAR NORTH', 'FAR NORTH'), ('LITTORAL', 'LITTORAL'), ('NORTH', 'NORTH'), ('NORTH WEST', 'NORTH WEST'), ('SOUTH', 'SOUTH'), ('SOUTH WEST', 'SOUTH WEST'), ('WEST', 'WEST')], default='I', max_length=15),
        ),
        migrations.AlterField(
            model_name='mainspecialty',
            name='specialty_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolidentification',
            name='support_number_one',
            field=models.CharField(default='693358642', max_length=15),
        ),
    ]
