# Generated by Django 5.0.1 on 2024-11-28 04:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0010_remove_campus_latitude_remove_campus_location_and_more'),
        ('noti_control', '0003_remove_complain_message_one_and_more'),
        ('prim_app_control', '0002_initial'),
        ('sec_app_control', '0002_initial'),
        ('user_control', '0003_customuser_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campus',
            new_name='CampusHigher',
        ),
        migrations.RenameModel(
            old_name='SchoolIdentification',
            new_name='SchoolIdentificationHigher',
        ),
        migrations.RenameModel(
            old_name='SchoolInfo',
            new_name='SchoolInfoHigher',
        ),
    ]
