# Generated by Django 5.0.1 on 2024-12-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0011_rename_campus_campushigher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolinfohigher',
            name='director',
        ),
        migrations.RemoveField(
            model_name='schoolinfohigher',
            name='version',
        ),
        migrations.AddField(
            model_name='schoolidentificationhigher',
            name='director',
            field=models.CharField(default='Edit', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolidentificationhigher',
            name='version',
            field=models.CharField(default='1.0.0', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolinfohigher',
            name='bg_logo_slip',
            field=models.ImageField(blank=True, null=True, upload_to='slip_higher/'),
        ),
        migrations.AddField(
            model_name='schoolinfohigher',
            name='bg_logo_transcript',
            field=models.ImageField(blank=True, null=True, upload_to='transcript_higher/'),
        ),
        migrations.AddField(
            model_name='schoolinfohigher',
            name='ca_limit',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='schoolinfohigher',
            name='colors',
            field=models.CharField(default='bg-teal-700, bg-teal-700', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolinfohigher',
            name='exam_limit',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='schoolinfohigher',
            name='landing_message_main',
            field=models.CharField(default='Welcome'),
        ),
        migrations.AddField(
            model_name='schoolinfohigher',
            name='logo_campus256',
            field=models.CharField(default='/images/logo/LogoEconneq.png'),
        ),
        migrations.AddField(
            model_name='schoolinfohigher',
            name='logo_campus512',
            field=models.CharField(default='/images/logo/LogoEconneq.png'),
        ),
        migrations.AddField(
            model_name='schoolinfohigher',
            name='method',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='schoolinfohigher',
            name='prefix',
            field=models.CharField(default='TEST', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolinfohigher',
            name='registration_seperate_tuition',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolinfohigher',
            name='resit_limit',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='schoolinfohigher',
            name='schoolfees_control',
            field=models.CharField(default='0.50, 0.80, 0.99, 1, 1, 1', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolinfohigher',
            name='welcome_message',
            field=models.CharField(default='Welcome To, Econneq', max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolinfohigher',
            name='address',
            field=models.CharField(default='Douala', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolinfohigher',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='schoolinfohigher',
            name='niu',
            field=models.CharField(default='NIU', max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolinfohigher',
            name='school_type',
            field=models.CharField(choices=[('Section-P', 'Section-P'), ('Section-S', 'Section-S'), ('Section-H', 'Section-H'), ('Section-V', 'Section-V')], default='Higher', max_length=15),
        ),
        migrations.AlterField(
            model_name='schoolinfohigher',
            name='telephone_one',
            field=models.CharField(default='670000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='schoolinfohigher',
            name='telephone_two',
            field=models.CharField(default='690000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='schoolinfohigher',
            name='town',
            field=models.CharField(default='Douala', max_length=10),
        ),
        migrations.AlterField(
            model_name='schoolinfohigher',
            name='website',
            field=models.CharField(default='https://test.e-conneq.com', max_length=45),
        ),
        migrations.DeleteModel(
            name='SettingHigher',
        ),
    ]
