# Generated by Django 5.0.1 on 2024-12-03 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0012_remove_schoolinfohigher_director_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campushigher',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='campushigher',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='schoolinfohigher',
            name='campus',
            field=models.CharField(choices=[('Campus-A', 'Campus-A'), ('Campus-B', 'Campus-B'), ('Campus-C', 'Campus-C'), ('Campus-D', 'Campus-D'), ('Campus-E', 'Campus-E'), ('Campus-F', 'Campus-F'), ('Campus-G', 'Campus-G'), ('Campus-H', 'Campus-H')], default='Campus-A', max_length=15),
        ),
        migrations.AlterModelOptions(
            name='schoolinfohigher',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddConstraint(
            model_name='schoolinfohigher',
            constraint=models.UniqueConstraint(fields=('campus', 'region'), name='school_info'),
        ),
        migrations.DeleteModel(
            name='CampusHigher',
        ),
    ]
