# Generated by Django 5.0.1 on 2024-12-05 01:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0014_remove_schoolinfohigher_school_info_and_more'),
        ('user_control', '0004_alter_preinscription_program_alter_program_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodule',
            name='file',
        ),
        migrations.RemoveField(
            model_name='coursemoduledetail',
            name='file',
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='files',
            field=models.ManyToManyField(related_name='modules', to='app_control.courseupload'),
        ),
        migrations.AddField(
            model_name='coursemoduledetail',
            name='files',
            field=models.ManyToManyField(related_name='details', to='app_control.courseupload'),
        ),
        migrations.AlterField(
            model_name='course',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='main_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='app_control.maincourse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='specialty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='app_control.specialty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='app_control.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursemoduledetail',
            name='course_module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='details', to='app_control.coursemodule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseupload',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='app_control.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainspecialty',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specialties', to='app_control.field'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='specialty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='publish', to='app_control.specialty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='app_control.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='user_control.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolinfohigher',
            name='email',
            field=models.CharField(max_length=40, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='schoolinfohigher',
            name='telephone',
            field=models.CharField(default='+237670000000', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+XXX XXXXXXXXX'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialties', to='app_control.level'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='main_specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialties', to='app_control.mainspecialty'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='payment_one',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='payment_three',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='payment_two',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='registration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialties', to='app_control.schoolinfohigher'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='tuition',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
