# Generated by Django 5.0.1 on 2024-12-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0015_remove_coursemodule_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfohigher',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=3.8436864, max_digits=9),
        ),
        migrations.AlterField(
            model_name='schoolinfohigher',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=11.4917376, max_digits=9),
        ),
    ]
