# Generated by Django 5.0.1 on 2024-10-30 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sec_app_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('session', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='Morning', max_length=10)),
                ('code', models.ImageField(blank=True, null=True, upload_to='code')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('secondary_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondaryprofile_classroom', to='sec_app_control.secondaryclassroom')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
