# Generated by Django 4.2.5 on 2023-12-20 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0003_course_date_assigned_course_hours_course_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_assigned',
            field=models.DateField(default=datetime.datetime(2023, 12, 20, 4, 48, 54, 343199, tzinfo=datetime.timezone.utc)),
        ),
    ]
