# Generated by Django 5.0.1 on 2024-10-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('GENERAL', 'GENERAL'), ('TECHNICAL', 'TECHNICAL'), ('COMMERCIAL', 'COMMERCIAL')], max_length=15)),
                ('academic_year', models.CharField(max_length=9)),
                ('registration', models.IntegerField(default=0)),
                ('tuition', models.IntegerField(default=0)),
                ('payment_one', models.IntegerField(default=0)),
                ('payment_two', models.IntegerField(default=0)),
                ('payment_three', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('FORM 1', 'FORM 1'), ('FORM 2', 'FORM 2'), ('FORM 3', 'FORM 3'), ('FORM 4', 'FORM 4'), ('FORM 5', 'FORM 5'), ('LOWERSIXTH', 'LOWERSIXTH'), ('UPPERSIXTH', 'UPPERSIXTH'), ('6eme', '6eme'), ('5eme', '5eme'), ('4eme', '4eme'), ('3eme', '3eme'), ('2nd', '2nd'), ('1erè', '1erè'), ('Terminal', 'Terminal')], max_length=15)),
                ('option', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SecondaryMainSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryPublish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_type', models.CharField(choices=[('term', 'term'), ('sequence', 'sequence')], default='I', max_length=15)),
                ('publish_item', models.CharField(choices=[('publish_seq_1', 'publish_seq_1'), ('publish_seq_2', 'publish_seq_2'), ('publish_seq_3', 'publish_seq_3'), ('publish_seq_4', 'publish_seq_4'), ('publish_seq_5', 'publish_seq_5'), ('publish_seq_6', 'publish_seq_6'), ('publish_term_1', 'publish_term_1'), ('publish_term_2', 'publish_term_2'), ('publish_term_3', 'publish_term_3')], default='I', max_length=15)),
                ('publish', models.BooleanField(default=False)),
                ('portal', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_1', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('seq_2', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('seq_3', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('seq_4', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('seq_5', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('seq_6', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('average_term_1', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('average_term_2', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('average_term_3', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('passed_1', models.BooleanField(default=False)),
                ('passed_2', models.BooleanField(default=False)),
                ('passed_3', models.BooleanField(default=False)),
                ('publish_seq_1', models.BooleanField(default=False)),
                ('publish_seq_2', models.BooleanField(default=False)),
                ('publish_seq_3', models.BooleanField(default=False)),
                ('publish_seq_4', models.BooleanField(default=False)),
                ('publish_seq_5', models.BooleanField(default=False)),
                ('publish_seq_6', models.BooleanField(default=False)),
                ('publish_term_1', models.BooleanField(default=False)),
                ('publish_term_2', models.BooleanField(default=False)),
                ('publish_term_3', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondarySubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_type', models.CharField(choices=[('General', 'General'), ('Practical', 'Practical'), ('Other', 'Other')], default='General', max_length=15)),
                ('subject_coefficient', models.IntegerField()),
                ('assigned', models.BooleanField(default=False)),
                ('date_assigned', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
