# Generated by Django 5.0.1 on 2024-10-30 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_control', '0002_initial'),
        ('sec_app_control', '0001_initial'),
        ('sec_user_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryclassroom',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_classroom_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondaryclassroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondary_classroom_school_info', to='app_control.schoolinfo'),
        ),
        migrations.AddField(
            model_name='secondaryclassroom',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_classroom_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondarylevel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_level_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondarylevel',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_level_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondaryclassroom',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_level', to='sec_app_control.secondarylevel'),
        ),
        migrations.AddField(
            model_name='secondarymainsubject',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_main_subject_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondarymainsubject',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_main_subject_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondarypublish',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_publish_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondarypublish',
            name='secondary_classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publish_secondary_classroom', to='sec_app_control.secondaryclassroom'),
        ),
        migrations.AddField(
            model_name='secondarypublish',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_publish_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondaryresult',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_result_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondaryresult',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='result_secondaryprofile', to='sec_user_control.secondaryprofile'),
        ),
        migrations.AddField(
            model_name='secondaryresult',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_result_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondarysubject',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_subject_lecturer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondarysubject',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_subject_class', to='sec_app_control.secondaryclassroom'),
        ),
        migrations.AddField(
            model_name='secondarysubject',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_subject_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondarysubject',
            name='main_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_subject_main_subject', to='sec_app_control.secondarymainsubject'),
        ),
        migrations.AddField(
            model_name='secondarysubject',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_subject_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondaryresult',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='result_secondary_subject', to='sec_app_control.secondarysubject'),
        ),
        migrations.AddConstraint(
            model_name='secondarylevel',
            constraint=models.UniqueConstraint(fields=('level', 'option'), name='unique_secondary_level'),
        ),
        migrations.AddConstraint(
            model_name='secondaryclassroom',
            constraint=models.UniqueConstraint(fields=('school', 'domain', 'level', 'academic_year'), name='unique_secondary_classroom'),
        ),
        migrations.AddConstraint(
            model_name='secondarypublish',
            constraint=models.UniqueConstraint(fields=('secondary_classroom', 'publish_type', 'publish_item'), name='unique_secondarypublish'),
        ),
        migrations.AddConstraint(
            model_name='secondarysubject',
            constraint=models.UniqueConstraint(fields=('classroom', 'main_subject'), name='unique_secondary_subject'),
        ),
        migrations.AddConstraint(
            model_name='secondaryresult',
            constraint=models.UniqueConstraint(fields=('subject', 'student'), name='unique_secondary_result'),
        ),
    ]
